In [2]:
import os    #Used to interact with the operating system.  #Read environment variables #Work with file paths #Access folders/files

import pandas as pd 
import numpy as np
from dotenv import load_dotenv                   # Load environment variables from .env file
from sqlalchemy import create_engine             # Used to create a database connection (MySQL, PostgreSQL, SQL Server, etc.).

load_dotenv()                                    # Load environment variables from .env file

pd.set_option('display.max_columns',100)       # Display all columns in the DataFrame
pd.set_option('display.width',200)

#MY SQL connection
engine = create_engine(os.getenv("DATABASE_URL"))
print("setup complete")          # Display all rows in the DataFrame

setup complete

## LOAD DATA FROM MY SQL

In [3]:
print("loading transaction from sql...")
tx = pd.read_sql("SELECT * FROM transactions", engine)  # Load data from the 'transactions' table in the database
print(f"{tx.shape[0]:,} rows, {tx.shape[1]:,} columns")  # Print the number of rows and columns loaded

print("loading identity from SQL...")
idn = pd.read_sql("SELECT * FROM identity", engine)  # Load data from the 'identity' table in the database
print(f"{idn.shape[0]:,} rows, {idn.shape[1]:,} columns")  # Print the number of rows and columns loaded

loading transaction from sql...
590,540 rows, 394 columns
loading identity from SQL...
144,233 rows, 41 columns

In [8]:
tx.describe()

,TransactionID,isFraud,TransactionDT,TransactionAmt,card1,card2,card3,card5,addr1,addr2,dist1,dist2,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,D14,D15,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V290,V291,V292,V293,V294,V295,V296,V297,V298,V299,V300,V301,V302,V303,V304,V305,V306,V307,V308,V309,V310,V311,V312,V313,V314,V315,V316,V317,V318,V319,V320,V321,V322,V323,V324,V325,V326,V327,V328,V329,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
count,5.905400e+05,590540.000000,5.905400e+05,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,...,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.00000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.00000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000
mean,3.282270e+06,0.034990,7.372311e+06,135.027176,9898.734658,357.071172,152.788941,197.841689,258.385512,77.142822,47.812842,14.772960,14.092458,15.269734,0.005644,4.092185,5.571526,9.071082,2.848478,5.144574,4.480240,5.240343,10.241521,4.076227,32.539918,8.295215,94.144827,88.937285,15.726349,99.955209,20.123384,8.651185,2.744036,18.531428,0.071185,108.021541,77.279051,5.921948,1.877978,6.078691,139.035379,0.527036,0.550891,0.568216,0.446137,0.462231,0.551145,0.565472,0.541667,0.548954,...,1.102989,1.659777,1.239891,0.942580,2.313816,1.433395,0.32821,0.089032,0.298823,0.171651,0.045409,0.051890,0.251756,0.283134,0.264202,0.999986,139.745873,408.674070,230.408498,10.995763,118.193256,4.20209,39.173114,21.305592,43.226087,26.749372,109.816313,247.601710,162.150103,18.372102,42.072278,28.326009,0.867421,1.827326,1.280797,0.008157,0.118678,0.041366,0.046965,0.183077,0.108196,100.647146,191.853488,141.489485,1.367592,8.250516,3.978644,7.718914,21.079388,14.042772
std,1.704744e+05,0.183755,4.617224e+06,239.162522,4901.170153,162.727883,13.791462,44.420452,132.506081,27.412877,243.261185,145.053578,133.569018,154.668899,0.150536,68.848459,25.786976,71.508467,61.727304,95.378574,16.674897,95.581443,94.336292,86.666218,129.364844,49.544262,157.551484,153.823451,48.557362,173.421595,64.900349,55.561666,27.610524,95.772821,0.218201,175.440514,153.627465,44.468349,22.576330,47.650790,195.785107,0.499269,0.550187,0.586500,0.529775,0.557751,0.550244,0.579551,0.530583,0.545346,...,0.768905,16.252375,3.775015,20.588608,39.526068,25.962685,3.26127,0.628346,3.175030,1.724201,0.289269,0.317977,0.481885,0.623603,0.528234,0.005205,2348.825854,4391.948740,3021.893722,116.253107,352.979909,102.37390,172.126681,95.804974,173.443984,116.734202,2270.010192,3980.002546,2793.315350,332.301482,473.494534,382.049311,21.031103,40.117339,27.678238,0.115469,1.504324,0.519749,0.601494,3.306056,1.785900,2335.112445,4198.067187,2991.618042,91.128152,146.195704,103.010107,250.367423,412.256263,306.317225
min,2.987000e+06,0.000000,8.640000e+04,0.251000,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-122.000000,0.000000,-83.000000,0.000000,0.000000,0.000000,0.000000,-53.000000,-83.000000,0.000000,-193.000000,-83.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.134635e+06,0.000000,3.027058e+06,43.321000,6019.000000,204.000000,150.000000,166.000000,184.000000,87.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.282270e+06,0.000000,7.306528e+06,68.769000,9678.000000,360.000000,150.000000,226.000000,272.000000,87.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3.429904e+06,0.000000,1.124662e+07,125.000000,14184.000000,512.000000,150.000000,226.000000,327.000000,87.000000,5.000000,0.000000,3.000000,3.000000,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000,2.000000,0.000000,2.000000,0.000000,12.000000,2.000000,121.000000,109.000000,11.000000,123.000000,8.000000,0.000000,0.000000,0.000000,0.000000,150.000000,57.000000,0.000000,0.000000,0.000000,251.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,151.306801,35.965801,0.000000,107.949997,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,3.577539e+06,1.000000,1.581113e+07,31937.391000,18396.000000,600.000000,231.000000,237.000000,540.000000,102.000000,10286.000000,11623.000000,4685.000000,5691.000000,26.000000,2253.000000,349.000000,2253.000000,2255.000000,3331.000000,210.000000,3257.000000,3188.000000,3188.000000,2918.000000,1429.000000,640.000000,640.000000,819.000000,869.000000,819.000000,873.000000,843.000000,1707.791626,0.958333,876.000000,670.000000,648.000000,847.000000,878.000000,879.000000,1.000000,8.000000,9.000000,6.000000,6.000000,9.000000,9.000000,8.000000,8.000000,...,67.000000,1055.000000,323.000000,869.000000,1286.000000,928.000000,93.00000,12.000000,93.000000,49.000000,11.000000,13.000000,16.000000,20.000000,16.000000,2.000000,108800.000000,145765.000000,108800.000000,55125.000000,55125.000000,55125.00000,55125.000000,4817.470215,7519.870117,4817.470215,93736.000000,134021.000000,98476.000000,104060.000000,104060.000000,104060.000000,880.000000,1411.000000,976.000000,12.000000,44.000000,18.000000,15.000000,99.000000,55.000000,160000.000000,160000.000000,160000.000000,55125.000000,55125.000000,55125.000000,104060.000000,104060.000000,104060.000000

In [20]:
idn.describe()

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,id_10,id_11,id_13,id_14,id_17,id_18,id_19,id_20,id_21,id_22,id_24,id_25,id_26,id_32
count,1.442330e+05,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000,144233.000000
mean,3.236329e+06,-10.170502,170645.238753,0.027677,-0.027102,1.533054,-6.356513,0.474829,-1.379608,0.047285,-0.156427,97.494307,42.418288,-191.188771,183.062468,4.453135,341.094694,389.960023,13.172464,0.573503,0.421304,11.727919,5.336157,14.259538
std,1.788496e+05,14.347949,159967.205312,0.406775,0.476273,5.126361,16.131925,3.273224,8.698546,0.710557,2.016105,14.856168,19.010751,184.891494,45.399611,6.658312,152.754962,166.685181,78.048494,3.248618,2.323969,63.765352,28.352705,13.497454
min,2.987004e+06,-100.000000,0.000000,-13.000000,-28.000000,-72.000000,-100.000000,-46.000000,-100.000000,-36.000000,-100.000000,0.000000,0.000000,-660.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.077142e+06,-10.000000,64159.000000,0.000000,0.000000,0.000000,-5.000000,0.000000,0.000000,0.000000,0.000000,100.000000,33.000000,-300.000000,166.000000,0.000000,254.000000,223.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.198818e+06,-5.000000,122552.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000,52.000000,-300.000000,166.000000,0.000000,321.000000,417.000000,0.000000,0.000000,0.000000,0.000000,0.000000,24.000000
75%,3.392923e+06,-5.000000,225093.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000,52.000000,0.000000,225.000000,13.000000,427.000000,533.000000,0.000000,0.000000,0.000000,0.000000,0.000000,24.000000
max,3.577534e+06,0.000000,999595.000000,10.000000,0.000000,52.000000,0.000000,61.000000,0.000000,25.000000,0.000000,100.000000,64.000000,720.000000,229.000000,29.000000,671.000000,661.000000,854.000000,44.000000,26.000000,548.000000,216.000000,32.000000

In [21]:
#Fix empty strings in object columns to NaN

print("Fixing empty strings in object columns to NaN...")
print(f"Before cleaning, transaction data has {tx.isnull().sum().sum():,} missing values and identity data has {idn.isnull().sum().sum():,} missing values.")

for col in tx.select_dtypes(include=['object']).columns:
    tx[col] = tx[col].replace(r'^\s*$', np.nan, regex=True)  # Replace empty strings with NaN in object columns

for col in idn.select_dtypes(include=['object']).columns:
    idn[col] = idn[col].replace(r'^\s*$', np.nan, regex=True)  # Replace empty strings with NaN in object columns    

print(f"After cleaning, transaction data has {tx.isnull().sum().sum():,} missing values and identity data has {idn.isnull().sum().sum():,} missing values.")

Fixing empty strings in object columns to NaN...
Before cleaning, transaction data has 3,204,208 missing values and identity data has 552,752 missing values.
After cleaning, transaction data has 3,204,208 missing values and identity data has 552,752 missing values.